//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiebwaldeApp.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    public sealed partial class CoreSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CoreSettings defaultInstance = ((CoreSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CoreSettings())));
        
        public static CoreSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal FIDDLExYARDxSIMxSPEEDxSETTING {
            get {
                return ((decimal)(this["FIDDLExYARDxSIMxSPEEDxSETTING"]));
            }
            set {
                this["FIDDLExYARDxSIMxSPEEDxSETTING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cyan")]
        public global::System.Drawing.Color SETxCOLORxTRACKxOCCUPIED {
            get {
                return ((global::System.Drawing.Color)(this["SETxCOLORxTRACKxOCCUPIED"]));
            }
            set {
                this["SETxCOLORxTRACKxOCCUPIED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color SETxCOLORxTRACKxNOTxINITIALIZED {
            get {
                return ((global::System.Drawing.Color)(this["SETxCOLORxTRACKxNOTxINITIALIZED"]));
            }
            set {
                this["SETxCOLORxTRACKxNOTxINITIALIZED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RoyalBlue")]
        public global::System.Drawing.Color SETxCOLORxTRACKxNOTxACTIVE {
            get {
                return ((global::System.Drawing.Color)(this["SETxCOLORxTRACKxNOTxACTIVE"]));
            }
            set {
                this["SETxCOLORxTRACKxNOTxACTIVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color SETxCOLORxTRACKxDISABLED {
            get {
                return ((global::System.Drawing.Color)(this["SETxCOLORxTRACKxDISABLED"]));
            }
            set {
                this["SETxCOLORxTRACKxDISABLED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color SETxCOLORxTRACKxDISABLEDxNOTxOCCUPIED {
            get {
                return ((global::System.Drawing.Color)(this["SETxCOLORxTRACKxDISABLEDxNOTxOCCUPIED"]));
            }
            set {
                this["SETxCOLORxTRACKxDISABLEDxNOTxOCCUPIED"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dummy {
            get {
                return ((string)(this["dummy"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Localdata\\\\Siebwalde\\\\Logging\\\\")]
        public string LogDirectory {
            get {
                return ((string)(this["LogDirectory"]));
            }
            set {
                this["LogDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28671")]
        public ushort FYSendingport {
            get {
                return ((ushort)(this["FYSendingport"]));
            }
            set {
                this["FYSendingport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28672")]
        public ushort FYReceivingport {
            get {
                return ((ushort)(this["FYReceivingport"]));
            }
            set {
                this["FYReceivingport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public ushort TrckSendingPort {
            get {
                return ((ushort)(this["TrckSendingPort"]));
            }
            set {
                this["TrckSendingPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10001")]
        public ushort TrckReceivingPort {
            get {
                return ((ushort)(this["TrckReceivingPort"]));
            }
            set {
                this["TrckReceivingPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.193")]
        public string TrckIpAddress {
            get {
                return ((string)(this["TrckIpAddress"]));
            }
            set {
                this["TrckIpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Localdata\\\\Siebwalde\\\\TrackAmplifier4.X\\\\dist\\\\Offset\\\\production\\\\TrackAmplifier4.X.production.hex")]
        public string TrackAmplifierFwPath {
            get {
                return ((string)(this["TrackAmplifierFwPath"]));
            }
            set {
                this["TrackAmplifierFwPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("amps: 1:1,2:2,3:3,4:4,5:5 ; routes: 1>2,2>3,3>4,3>5,4>1,5>1")]
        public string BlockTopologyConfig {
            get {
                return ((string)(this["BlockTopologyConfig"]));
            }
            set {
                this["BlockTopologyConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1:1.01+1.02:1, 2:1.03+1.04:2, 3:1.05+1.06:3, 4:1.07+1.08:4, 5:1.09+1.10:5")]
        public string KoploperBlockMapConfig {
            get {
                return ((string)(this["KoploperBlockMapConfig"]));
            }
            set {
                this["KoploperBlockMapConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseFakeHardwareAdapters {
            get {
                return ((bool)(this["UseFakeHardwareAdapters"]));
            }
            set {
                this["UseFakeHardwareAdapters"] = value;
            }
        }
    }
}
